# fly.toml app configuration file generated for orangecms on 2023-05-21T23:43:21+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "orangecms"
primary_region = "sin"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "orangecms.fly.dev"
  PORT = "8080"
