# fly.toml app configuration file generated for orangecms on 2023-05-22T09:45:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "orangecms"
primary_region = "sin"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"
  strategy = "rolling"

[env]
  PHX_HOST = "orangecms.fly.dev"
  PHX_SERVER = "true"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
