# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Fly

on:
  push:
    branches: [ "main" ]
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
  
permissions:
  contents: read

jobs:
  deploy:
      name: Deploy app to Fly.io
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy

